### ISSUE TITLE
Is there an option to see all possible values of `solver` allowed to `ROI_solve`?

### ISSUE THREAD

**Issue by JanaJarecki** [FlorianSchwendinger/ROI_docs#5]
Hi!
Is there an option in `ROI` to see all possible allowed string values of the `solver` argument to `ROI_solve()`?

`ROI::ROI_available_solvers()$Package` prints the package name which need not be equal to the name of the argument `solver`, which might for instance be something like `"nloptr.lbfgs"`. Maybe I missed it in the documentation somewhere?

Thank you :)
Jana

**Comment by FlorianSchwendinger** [comment]
Hello!

You can see all the allowed solver arguments with
`ROI_registered_solver_control("nloptr.lbfgs")`

	                   control     roi_control
	1                  dry_run         dry_run
	2                       x0           start
	3                 xtol_rel         rel_tol
	4                 xtol_abs         abs_tol
	5                  maxeval        max_iter
	6                  maxtime        max_time
	7              print_level verbosity_level
	8                  stopval               X
	9                 ftol_rel               X
	10                ftol_abs               X
	11    tol_constraints_ineq               X
	12      tol_constraints_eq               X
	13       check_derivatives               X
	14   check_derivatives_tol               X
	15 check_derivatives_print               X
	16       print_options_doc               X
	17              population               X
	18                 ranseed               X
	19              local_opts               X
	20              randomized               X
	21                 precond               X
	22                 restart               X
	23                    args               X

The name shown under control gives you the arument used in the `nloptr` package,
and `roi_control` gives you the unified name in ROI. We don't strictly enforce to use
the unified name which means if you would use "x0" instead of "start" ROI would 
not complain. But if you use "maximum_time" instead of "max_time" or "maxtime"
you get a warning, telling you that we do not know the argument "maximum_time".
It is just a warning since this means if we forgot to register a control argument,
you could still use it.
